
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: rashmi200/spring-backend:1.0
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "docker"
        ports:
        - containerPort: 8080
