services:
  mysqldb:
    image: mysql:8
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: aaAA11!!
      MYSQL_DATABASE: test
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: .
    container_name: backend
    depends_on:
      - mysqldb
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker

  client:
    build: ./client
    container_name: client
    depends_on:
      - backend
    ports:
      - "3001:3000"

volumes:
  mysql_data:
    
